challenges = [
    "Zig Zag",
    "Swing",
    "Scale",
    "Pop The Lock",
    "22 Seconds",
    "Twist",
    "Amazing Ninja",
    "Tappy Climb",
    "Gravity Switch",
    "Ballz",
    "QuizUp",
    "Down The Mountain",
    "Circle",
    "Stack",
    "2048",
    "Skyward",
    "Don't Fall",
    "Ketchapp Soccer",
    "Rush Hero",
    "Stairs",
    "Roller Coaster",
    "Intense",
    "Knife Hit",
    "Ball Shoot",
    "Dunk Line",
    "Flippy",
    "Piano Tiles",
    "Bouncy Hoops",
    "Horizon",
    "Streakbound",
    "Three-In-One",
    "Chicken Scream",
    "Waves!",
    "Car VS Cops",
    "Magic River",
    "Pinball Sniper",
    "MinerZ",
    "Spin",
    "Flappy Dunk",
    "Flash Challenges",
    "Super Smash Flash 2",
    "Multitask",
    "Kanye Zone",
    "Pac-Man",
    "Entanglement",
    "Casanova",
    "GIRP",
    "Snowbowling",
    "Candy and Clyde",
    "Tetris",
    "Grid 16",
    "Pokemon Showdown",
    "Between Water and Fire",
    "Sunny Day Sky",
    "Galaga",
    "Hot Air Bloon",
    "Semantris",
    "Johnny Upgrade",
    "Oh, The Huge Manatee!",
    "Tilt",
    "Puzzle Challenges",
    "Puzzled",
    "Slide Puzzle",
    "Jigsaw Puzzle",
    "Word Search",
    "Zebra Puzzle",
    "Puzzle Ball",
    "Arrange Puzzle",
    "Design Challenges",
    "Tribal Designs",
    "Roasts of Passage",
    "Hero Challenges",
    "Survivor Trivia",
    "Decoding",
    "Know Your Continent",
    "Word Unscramble",
    "Fast Math",
    "Lookalikes",
    "Sporcle Quiz",
    "Tower of Hanoi",
    "Speed Counting",
    "Survey Says",
    "Invisible Maze",
    "City Unscramble",
    "Chess",
    "Survivor Classics",
    "Survivor Auction",
    "Coconut Challenge",
    "Touchy Subjects",
    "Fallen Comrades",
    "Miscellaneous Challenges",
    "Trivia Zone",
    "Hangman",
    "Minority Rules",
    "Timed Trivia",
    "Exclusive Answer",
    "Spam Off",
    "Scavenger Hunt",
    "Trivia Showdown",
    "Retyping Challenge",
    "Word Ladder",
    "Correct Order",
    "Name That Survivor",
    "Castaway Clues",
    "Invasion",
    "Name Link",
    "Survivor Labyrinth",
    "Typing Speed Test",
    "Tug of War",
    "Word Chain",
    "Name That Flag",
    "Solve For x",
    "YouTube Hunter",
    "Count It Out",
    "Firemaking Challenges",
    "The Pit",
    "Fire Puzzle",
    "Final Immunity Challenge",
    "Up And Up",
    "The Final Test",
    "Castaway Matching",
    "NyanNyanNyan",
    "Numbers Game",
    "Redemption Duel",
]
